services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
#     depends_on:
#       - backend

#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     environment:
#       - DATABASE_URL=postgresql://postgres:postgres@db:5432/metin2hub
#     depends_on:
#       - db

#   db:
#     image: postgres:16
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: metin2hub
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
